jstestdriver --config Bookmarks.conf --tests all --captureConsole --testOutput %~dp0\results
jstestdriver --config bugs.conf --tests all --captureConsole --testOutput %~dp0\results
jstestdriver --config common.conf --tests all --captureConsole --testOutput %~dp0\results
jstestdriver --config Daisy202Loader.conf --tests all --captureConsole --testOutput %~dp0\results
jstestdriver --config javascript-stacktrace.conf --tests all --captureConsole --testOutput %~dp0\results
jstestdriver --config jQueryMobile.conf --tests all --captureConsole --testOutput %~dp0\results
jstestdriver --config log4javascript.conf --tests all --captureConsole --testOutput %~dp0\results
jstestdriver --config NLBServer.conf --tests all --captureConsole --testOutput %~dp0\results
jstestdriver --config SmilPlayer.conf --tests all --captureConsole --testOutput %~dp0\results
jstestdriver --config SmilPlayerUI.conf --tests all --captureConsole --testOutput %~dp0\results
jstestdriver --config soundmanager2.conf --tests all --captureConsole --testOutput %~dp0\results
